# Generated by Django 3.2 on 2022-12-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='carts_id',
            new_name='CARTSID',
        ),
    ]
