# Generated by Django 3.2 on 2022-12-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_rename_carts_id_carts_cartsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='carts',
        ),
        migrations.AddField(
            model_name='pictures',
            name='cartsid',
            field=models.CharField(db_index=True, default='1', max_length=200),
        ),
        migrations.DeleteModel(
            name='carts',
        ),
    ]
